name: Publish to docker hub

on:
  push:
    branches: [ main ]

jobs:
  docker_publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build Devi ServiceHosts Discord Interaction
      run: docker build . --file ./Devi.ServiceHosts.Discord.Interaction/Dockerfile --tag thoenissen/devi.servicehosts.discord.interaction:latest
      
    - name: Build Devi ServiceHosts Discord Worker
      run: docker build . --file ./Devi.ServiceHosts.Discord.Worker/Dockerfile --tag thoenissen/devi.servicehosts.discord.worker:latest

    - name: Build Devi ServiceHosts IdentityServer 
      run: docker build . --file ./Devi.ServiceHosts.IdentityServer/Dockerfile --tag thoenissen/devi.servicehosts.identityserver:latest

    - name: Build Devi ServiceHosts WebApi 
      run: docker build . --file ./Devi.ServiceHosts.WebApi/Dockerfile --tag thoenissen/devi.servicehosts.webapi:latest

    - name: Build Devi ServiceHosts WebApp
      run: docker build ./devi.servicehosts.webapp --file ./devi.servicehosts.webapp/Dockerfile --tag thoenissen/devi.servicehosts.webapp:latest

    - name: Push ServiceHosts Discord Interaction
      run: docker push thoenissen/devi.servicehosts.discord.interaction
      
    - name: Push ServiceHosts Discord Worker
      run: docker push thoenissen/devi.servicehosts.discord.worker

    - name: Push ServiceHosts IdentityServer
      run: docker push thoenissen/devi.servicehosts.identityserver

    - name: Push ServiceHosts WebApi
      run: docker push thoenissen/devi.servicehosts.webapi

    - name: Push ServiceHosts WebApp
      run: docker push thoenissen/devi.servicehosts.webapp