name: Publish to docker hub

on:
  push:
    branches: [ main ]

jobs:
  docker_publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build Devi ServiceHosts Discord
      run: docker build . --file ./Devi.ServiceHosts.Discord/Dockerfile --tag thoenissen/devi.servicehosts.discord:latest

    - name: Build Devi ServiceHosts Discord
      run: docker build . --file ./Devi.ServiceHosts.WebApi/Dockerfile --tag thoenissen/devi.servicehosts.webapi:latest

    - name: Push ServiceHosts Discord
      run: docker push thoenissen/devi.servicehosts.discord

    - name: Push ServiceHosts WebApi
      run: docker push thoenissen/devi.servicehosts.webapi